### ISSUE TITLE
Having an issue with custom devise controllers

### ISSUE THREAD

**Issue by mattfiocca** [neo4jrb/devise-neo4j#24]
Hello,

Please forgive any ignorance, as this is my first go at using devise as a whole, let alone with our neo4j database. 

Ok, i've found myself needing to customize the views for the devise routes, and also needing to set some custom data from the controllers into these views. In order to do that, I was lead to do this:

``` bash
rails g devise:views
rails g devise:controllers webusers # users model `Webuser`, scoping accordingly
``` 

The reason i asked devise for the controllers was so that I could add custom `before_action` hooks in these devise routes, to set some data for the views. 

Now, these controllers extend `Devise::XController`, example: `class Webusers::RegistrationsController < Devise::RegistrationsController` and I'm getting `validatable` errors when trying to visit my sign up page, and I can't figure out where i'm going wrong. Is it because this was a devise controller generation, and not a neo4j-devise controller generation (though that option doesn't appear available)? 

Anyway, here's my error:
```
NoMethodError in Webusers::RegistrationsController#new

undefined method `validatable?' for nil:NilClass

Extracted source (around line #170):

# Sets minimum password length to show to user
  def set_minimum_password_length
    if devise_mapping.validatable? # <- ERROR HIGHLIGHTED HERE
      @minimum_password_length = resource_class.password_length.min
    end
  end
```

Here's the top few lines from the stack:

```
devise (4.2.0) app/controllers/devise_controller.rb:170:in `set_minimum_password_length'
activesupport (4.2.6) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
```

Here is my controller:
``` ruby
class Webusers::RegistrationsController < Devise::RegistrationsController

	before_action :load_custom_data

	private

	def load_custom_data
		# loading my @vars's here
	end
end
```

Model (the default after running `rails g neo4j:devise Webuser`):
``` ruby
class Webuser
  include Neo4j::ActiveNode
     property :username, type: String
     property :facebook_token, type: String
     index :facebook_token
     property :created_at, type: DateTime
     property :updated_at, type: DateTime
     property :email, type: String, null: false, default: ""
     index :email
     property :encrypted_password

     ## Rememberable
     property :remember_created_at, type: DateTime
     property :remember_token
     index :remember_token

     ## Recoverable
     property :reset_password_token
     index :reset_password_token
     property :reset_password_sent_at, type: DateTime

     ## Trackable
     property :sign_in_count, type: Integer, default: 0
     property :current_sign_in_at, type: DateTime
     property :last_sign_in_at, type: DateTime
     property :current_sign_in_ip, type:  String
     property :last_sign_in_ip, type: String

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end
```

Layout (views/layouts/devise.html.erb). The `@var`'s I actually need to pass in from the controller live with `partials/header`.
``` erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield :site_title %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= csrf_meta_tags %>

		<link rel="shortcut icon" href="<%= image_path 'favicon.ico' %>">
		<%=stylesheet_link_tag "print", media: "print"%>
		<%=stylesheet_link_tag "account", media: "screen"%>

		<script>
			window.api_url = '<%=api_url%>'
		</script>

		<%=javascript_include_tag "account-head" %>
	</head>
	<body ng-app="MainApp" ng-controller="BaseController">

		<%=render "partials/header"%>

		<main ng-controller="AccountsController">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
			<%= yield %>
		</main>

		<%=render "partials/footer"%>

		<%=javascript_include_tag "account-footer"%>
		<%=javascript_include_tag "tracking"%>

	</body>
</html>
```

View (default after running `rails g devise:views`)
``` erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>
```

Devise setup (default from running `rails g devise:install --orm=neo4j`):
``` ruby
Devise.setup do |config|
  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
  require 'devise/orm/neo4j'
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  config.skip_session_storage = [:http_auth]
  config.stretches = Rails.env.test? ? 1 : 11
  config.reconfirmable = true
  config.expire_all_remember_me_on_sign_out = true
  config.password_length = 6..128
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
  config.reset_password_within = 6.hours
  config.sign_out_via = :delete
end
```

Is there anything specific to my setup that appears wonky? 

Any advice to what i'm looking to achieve is greatly appreciated.

**UPDATE**

Here's my routes.rb, and this issue occurs when browsing to `/register`
``` ruby
Rails.application.routes.draw do

	devise_for :webusers, :controllers => {
		confirmations: 'webusers/confirmations',
		passwords: 'webusers/passwords',
		registrations: 'webusers/registrations',
		sessions: 'webusers/sessions',
		unlocks: 'webusers/unlocks'
	}

	devise_scope :webusers do
		get '/register', to: 'webusers/registrations#new', as: :register
		get '/profile', to: 'webusers/registrations#edit', as: :profile
		get '/login', to: 'webusers/sessions#new', as: :login
		get '/logout', to: 'webusers/sessions#destroy', as: :logout
	end
	
	...
	
end
```

**Comment by mattfiocca** [comment]
i've at least figured out a work around, in that `devise_scope` was messing this up for us. So, i've just removed the custom scope, and things are working like they should.

**Comment by cheerfulstoic** [comment]
Glad that you were able to figure something out ;)  Let me know if you'd like to look deeper at the issue sometime

**Comment by francisli** [comment]
For anyone that stumbles upon this thread due to a web search, the problem above can be solved by passing to devise_scope the _singular_ form of the user resource model:

``` ruby
devise_scope :webuser do
  ...
end
```

**Comment by cheerfulstoic** [comment]
Thanks!

**Comment by heavenlypeach** [comment]
I am having the same issue but the solution provided does not work for me.
This is my first time using devise. I have a simple rspec controller test to check if a get request to register route returns a status of 200. But instead I keep getting this ridiculous error.
```Ruby
Users::RegistrationsController GET #new returns http success
     Failure/Error: process :new, method: :get
     NoMethodError:
         undefined method `validatable?' for nil:NilClass
    
.rvm/gems/ruby-2.3.2/gems/devise-4.2.0/app/controllers/devise_controller.rb:170:in `set_minimum_password_length'
```

My Routes
```Ruby
  devise_for :users,
  :controllers => { :registrations => 'users/registrations' },
  skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]
  devise_scope :user do
    get 'register', to: 'users/registrations#new', as: :signup
    post 'register', to: 'users/registrations#create', as: :""
    delete 'register', to: 'users/registrations#create', as: :""
  end
```

My Registrations Controller
```Ruby
class Users::RegistrationsController < Devise::RegistrationsController
  def new
  end

  def create
  end

  def destroy
  end
end
```

My Test
```Ruby
require 'rails_helper'

RSpec.describe Users::RegistrationsController, type: :controller do

  describe "GET #new" do
    it "returns http success" do
      process :new, method: :get
      expect(response).to have_http_status(:success)
    end
  end
end
```

**Comment by heavenlypeach** [comment]
I figured out why I was having this problem. I forgot to add the following code to my test.
```Ruby
  before(:each) {
    @request.env["devise.mapping"] = Devise.mappings[:user]
  }
```

**Comment by cheerfulstoic** [comment]
Great ;) Devise has so many knobs to tweak, but it seems like once you bang your head for a while and find the right one it's all smooth.  Best of luck! :)

**Comment by kimiya66** [comment]
hello,
can some one please help me?
I got this error : NoMethodError (undefined method `to_datetime' for nil:NilClass) when I try to log out from the user or when I want to reset the password. is this problem because of outdated rails? or do you have any idea?

**Comment by cheerfulstoic** [comment]
Hey @kimiya66 I don't know that I could say without more information.  Can you provide a backtrace for the error?
