### ISSUE TITLE
rake neo4j:migrate error

### ISSUE THREAD

**Issue by nomasprime** [neo4jrb/devise-neo4j#40]
```
== 20230314133654 CreateUser: running... =======================================
 CYPHER CREATE CONSTRAINT FOR (n:`User`) REQUIRE n.`uuid` IS UNIQUE
== 20230314133654 CreateUser: migrated (0.1260s) ===============================

== 20230314133654 DeviseCreateUserConstraintsAndIndexes: running... ============
rake aborted!
Neo4j::Driver::Exceptions::ClientException: Node(1) already exists with label `ActiveGraph::Migrations::SchemaMigration` and property `migration_id` = '20230314133654'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/neo4j-ruby-driver-4.4.3/ruby/neo4j/driver/internal/util/result_holder.rb:38:in `result!'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/neo4j-ruby-driver-4.4.3/ruby/neo4j/driver/internal/internal_result.rb:15:in `has_next?'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/neo4j-ruby-driver-4.4.3/lib/neo4j/driver/synchronizable.rb:16:in `block (4 levels) in with_sync_wrapper'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/async-2.4.2/lib/kernel/sync.rb:20:in `Sync'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/neo4j-ruby-driver-4.4.3/lib/neo4j/driver/synchronizable.rb:16:in `block (3 levels) in with_sync_wrapper'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/neo4j-ruby-driver-4.4.3/ruby/neo4j/driver/internal/internal_result.rb:31:in `each'
/Users/nomasprime/Organisations/playtimestudios/contacts/server/vendor/bundle/ruby/3.2.0/gems/activegraph-11.3.1/lib/active_graph/core/result.rb:16:in `each'
```

**Comment by nomasprime** [comment]
Downgraded to Rails 6 in the hope this would work OTB, but no such luck.

```
Some schema elements were defined by the model (which is no longer supported), but they do not exist in the database. Run the following to create them if you haven't already:
rake neo4j:generate_schema_migration[constraint,User,uuid]
And then run `rake neo4j:migrate`
```

Following causes migrations to hang.

Spent hours trying to get this to work now. Rails and Neo4J might be a no go, very unproductive.
